server:
  port:

# 定義map集合
user:
  name: bill
  age: 23
  password: 123456

# 定義array/list/set
hobby:
  - java
  - c
  - game
  - listening music


# file name
spring:
  application:
    name: Mybatis_startup
# database info
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_01
    username: root
    password: 1234

# set file size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
# logback and a_column --> aColumn
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# google的cloud storage 配置
google:
  cloud-storage:
    projectID: JavaProject
    bucketName: fileupload-java

Set-Cookie:
  myCookie: value
  SameSite: None
  Secure:


